version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    restart: always

  frontend:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "3000:80"
    restart: always
